---
- name: Install Docker
  hosts: all
  become: true
  tasks:
  - name: Install Docker depend
    apt:
     name: ca-certificates, curl, gnupg, lsb-release
     state: present
     update_cache: true
  - name: Create dir for GPG key
    file:
     path: /etc/apt/keyrings
     state: directory
     mode: '0664'
  - name: Get and install GPG key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     keyring: /etc/apt/keyrings/docker.gpg
     state: present
  - name: Create repository Docker to apt
    lineinfile:
     path: /etc/apt/sources.list.d/docker.list
     line: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
     create: yes
     state: present
     mode: '0664'
  - name: Install Docker-ce
    apt:
     name: docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin
     update_cache: true
  - name: Add user to group
    user:
     name: zkaster
     append: true
     groups: docker
